# Generated by Django 3.0.7 on 2020-07-05 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userK.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='addquestion.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premoderate', models.BooleanField(default=True)),
                ('difficulty', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50')], default='30', max_length=2)),
                ('question', models.TextField(max_length=256)),
                ('corectAnsw', models.CharField(max_length=64)),
                ('answer2', models.CharField(max_length=64)),
                ('answer3', models.CharField(max_length=64)),
                ('answer4', models.CharField(max_length=64)),
                ('author', models.ForeignKey(on_delete=models.SET(userK.models.CustomUser), to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='addquestion.Theme')),
            ],
        ),
    ]
