# Generated by Django 3.0.7 on 2020-07-08 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premoderate', models.BooleanField(default=True)),
                ('difficulty', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50')], default='30', max_length=2)),
                ('question', models.TextField(max_length=350)),
                ('corectAnsw', models.CharField(max_length=64)),
                ('answer2', models.CharField(max_length=64)),
                ('answer3', models.CharField(max_length=64)),
                ('answer4', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('category', models.ForeignKey(db_column='category', default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='addquestion.Category')),
            ],
        ),
    ]
