# Generated by Django 3.1 on 2020-08-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=150, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premoderate', models.BooleanField(default=True, verbose_name='На модерации')),
                ('difficulty', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50')], default='30', max_length=2, verbose_name='Сложность')),
                ('question', models.TextField(max_length=350, verbose_name='Вопрос')),
                ('corectAnsw', models.CharField(max_length=64, verbose_name='Правильный ответ')),
                ('answer2', models.CharField(max_length=64, verbose_name='Ответ2')),
                ('answer3', models.CharField(max_length=64, verbose_name='Ответ3')),
                ('answer4', models.CharField(max_length=64, verbose_name='Ответ4')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, verbose_name='Тема')),
                ('category', models.ForeignKey(db_column='category', default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='addquestion.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
    ]
