# Generated by Django 3.0.7 on 2020-07-08 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userK.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addquestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='author',
            field=models.ForeignKey(db_column='username', on_delete=models.SET(userK.models.CustomUser), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(db_column='category', default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='addquestion.Category'),
        ),
        migrations.AddField(
            model_name='questions',
            name='theme',
            field=models.ForeignKey(db_column='theme', default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='addquestion.Theme'),
        ),
    ]
