# Generated by Django 3.1 on 2020-09-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200908_0816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invites',
        ),
    ]
