# Generated by Django 3.0.7 on 2020-07-30 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('parrent_account_id', models.CharField(blank=True, default='', max_length=20, verbose_name='Родительский аккаунт')),
                ('child_account', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Никнейм')),
                ('is_active', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('firstName', models.CharField(max_length=128, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('hideMyName', models.BooleanField(default=False)),
                ('balance', models.CharField(default=0.0, max_length=128, verbose_name='Баланс')),
                ('gender', models.CharField(choices=[('Male', 'М'), ('Female', 'Ж')], max_length=10, verbose_name='Пол')),
                ('birthday', models.DateField(null=True, verbose_name='Дата рождения')),
                ('country', models.CharField(choices=[('RU', 'Россия'), ('UK', 'Украина'), ('BY', 'Беларусь'), ('KZ', 'Казахстан')], max_length=128, verbose_name='Страна')),
                ('area', models.CharField(max_length=128, verbose_name='Область')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('phoneNumber', models.CharField(max_length=20, null=True, unique=True, verbose_name='Телефон')),
                ('swPlace', models.CharField(blank=True, max_length=128, verbose_name='Место работы / учёбы: ВУЗ / колледж / школа - класс')),
                ('opLVL', models.CharField(default=0, max_length=128, verbose_name='Опыт(Очки уровня)')),
                ('league', models.CharField(blank=True, choices=[('l1', 'Школьная лига'), ('l2', 'Лига колледжей'), ('l3', 'Студенческая лига'), ('l4', 'Высшая лига'), ('l5', 'Премьер-лига'), ('l6', 'Супер-лига')], max_length=128, verbose_name='Лига')),
                ('scoreHistory', models.TextField(default=[], verbose_name='История счета')),
                ('countMaster', models.CharField(default=0, max_length=128, verbose_name='Счетчик подсказок мастера')),
                ('countDelTwoAnsw', models.CharField(default=0, max_length=128, verbose_name='Счетчик подсказок "Убрать два ответа"')),
                ('countChance', models.CharField(default=0, max_length=128, verbose_name='Счетчик подсказок "Второй шанс"')),
                ('countSkipQuest', models.CharField(default=0, max_length=128, verbose_name='Счетчик пропуска вопроса')),
                ('countRights', models.CharField(default=0, max_length=128, verbose_name='Счетчик правильных ответов')),
                ('countWrongs', models.CharField(default=0, max_length=128, verbose_name='Счетчик неправильныых ответов')),
                ('countTotalGames', models.CharField(default=0, max_length=128, verbose_name='Счетчик игр')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
