# Generated by Django 3.0.7 on 2020-07-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
