# Generated by Django 3.0.7 on 2020-08-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userK', '0002_auto_20200731_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_free_member',
            field=models.BooleanField(default=False, verbose_name='Льготник'),
        ),
    ]
