# Generated by Django 3.0.7 on 2020-06-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userK', '0002_auto_20200627_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='schClass',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='studyPlace',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='workPlace',
        ),
        migrations.AddField(
            model_name='customuser',
            name='swPlace',
            field=models.CharField(blank=True, max_length=128, verbose_name='Место работы / учёбы: ВУЗ / колледж / школа - класс'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='league',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Лига'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='parrent_account_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Родительский аккаунт'),
        ),
    ]
