# Generated by Django 3.0.7 on 2020-06-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userK', '0003_auto_20200628_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hideMyName',
            field=models.BooleanField(default=False),
        ),
    ]
