# Generated by Django 3.0.7 on 2020-06-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userK', '0005_auto_20200629_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='lvl',
            new_name='opLVL',
        ),
    ]
