# Generated by Django 3.0.7 on 2020-06-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userK', '0006_auto_20200629_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='league',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rating',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='opLVL',
            field=models.CharField(default=0, max_length=128, verbose_name='Опыт(Очки уровня)'),
        ),
    ]
