# Generated by Django 3.1 on 2020-09-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userK', '0006_auto_20200908_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_in_the_team',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], max_length=1, verbose_name='Номер в команде'),
        ),
    ]
