# Generated by Django 3.0.7 on 2020-08-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleTitle', models.CharField(max_length=100, verbose_name='Название')),
                ('ruleDescription', models.TextField(verbose_name='Полный текст')),
            ],
        ),
    ]
