# Generated by Django 3.1 on 2020-08-09 10:57

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='NullUserName', max_length=128)),
                ('image', models.ImageField(upload_to=media.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MainBanner', max_length=128, unique=True)),
                ('image', models.ImageField(upload_to='static/mediacontent/banners')),
            ],
        ),
    ]
