# Generated by Django 3.0.7 on 2020-06-29 07:05

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20200629_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=media.models.user_directory_path),
        ),
    ]
