# Generated by Django 3.0.7 on 2020-07-03 23:30

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20200629_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='NullUserName', max_length=128)),
                ('image', models.ImageField(upload_to=media.models.user_directory_path)),
            ],
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='Avatar',
        ),
    ]
