# Generated by Django 3.0.7 on 2020-07-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20200704_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='banner',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='user',
        ),
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(default='banner', max_length=128),
        ),
    ]
