# Generated by Django 3.0.7 on 2020-07-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20200704_0251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
