# Generated by Django 3.0.7 on 2020-07-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='NullUserName', max_length=128)),
                ('image', models.ImageField(upload_to='C:\\Users\\Alex\\Desktop\\Kolibrina\\project\\static/mediacontent/banner')),
            ],
        ),
    ]
