# Generated by Django 3.0.7 on 2020-07-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='user',
        ),
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(default='Banner', max_length=128),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\Alex\\Desktop\\Kolibrina\\project\\static/mediacontent/banners'),
        ),
    ]
