# Generated by Django 3.0.7 on 2020-07-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20200704_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(default='Banner', max_length=128, unique=True),
        ),
    ]
