# Generated by Django 3.0.7 on 2020-07-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20200704_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(default='MainBanner', max_length=128, unique=True),
        ),
    ]
