# Generated by Django 3.1 on 2020-09-08 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20200908_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorehistory',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 8, 6, 42, 37, 679863)),
        ),
    ]
